name: .NET Core Release

on:
  push:
    tags:
      - 'v*'

env:
  NUGET_UPLOAD_URL: https://nuget.pkg.github.com/carbonfrost/
  NUGET_SOURCE_URL: https://nuget.pkg.github.com/carbonfrost/index.json
  NUGET_USER_NAME: ${{ github.actor }}
  NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com/Carbonfrost/index.json

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
       nuget-version: latest

    - name: Check release requirements
      run: make release/requirements

    - name: Configure dotnet and NuGet
      run: make dotnet/configure

    - name: Restore with dotnet
      run: make dotnet/restore

    - name: Build with dotnet
      run: make -- -dotnet/build

    - name: Pack with dotnet
      run: make -- -dotnet/pack

    - name: Publish the package to GitHub Package Repository
      run: make -- -dotnet/push
